### PR TITLE
Update alpine to 3.7

### PR DESCRIPTION
**Pull request by grayside**
Tried to keep the commits separate and clean. Alpine 3.6 required the upgrade to glibc, I see nothing in the issue queue for glibc indicating that Alpine 3.7 is an issue. 3.7 is latest stable release.

Amongst other things, this bumps the version of many Alpine packages, including getting nginx up to 1.12.

I started putting this together because I wanted to add confd and nginx, but the official nginx image looks more comprehensive anyway so I'm thinking I might manage it by adding confd to that instead.

### CODE REVIEW

**Review by tekante — APPROVED** [review]
Looks good to me. I presume the previous comment indicating confd was already present in this image was spurious (thus it's removal). Towards your original goal of wanting to add confd and nginx, I think confd could be appropriate for the light service base (not sure how we wound up with the comment indicating it was there but without it actually being present) but nginx seems like it may make more sense as a separate image using this one as a base. Suppose that is dependent upon what we think the minimum common components of a base docker container should be. For me, I think nginx takes it from "common docker service container" to "common web service docker service container".

**Comment by febbraro** [comment]
Do we want to take the opportunity to update s6 to more a recent version?

**Comment by grayside** [comment]
@tekante correct about confd, not sure if it was previously in the image, but it's not now. This image is meant to be our lean base for "normal" Docker images, lean & specialized. I'm not advocating for adding confd or nginx to this, rather I have an nginx proxy image I'm working on based on this.

@febbraro good point, I'll take a look at s6.

**Comment by febbraro** [comment]
I think confd was removed because there were conflicts with alpine and confd.  My brain is foggy on this.

**Comment by grayside** [comment]
Upgraded S6. There are 2-3x the number of environment options as there were  in 1.12, I added one that struck me as important.

I tested this against my nginx proxy image and it's working as expected.

**Comment by grayside** [comment]
> I think confd was removed because there were conflicts with alpine and confd. My brain is foggy on this.

I added confd v0.11.0 to my image and it worked fine. Upgrading it to v0.14 now.

**Review by febbraro — APPROVED** [review]

**Pull request merged**
